// <auto-generated />
using System;
using FCanteen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCanteen.Data.Migrations
{
    [DbContext(typeof(FCanteenContext))]
    [Migration("20260915033247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCanteen.Data.Entities.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CM01",
                            IsAvailable = true,
                            Name = "Cơm gà xối mỡ",
                            Price = 35000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CM02",
                            IsAvailable = true,
                            Name = "Cơm sườn bì chả",
                            Price = 32000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CM03",
                            IsAvailable = true,
                            Name = "Cơm tấm sườn nướng",
                            Price = 30000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CM04",
                            IsAvailable = true,
                            Name = "Cơm chiên dương châu",
                            Price = 28000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CM05",
                            IsAvailable = true,
                            Name = "Cơm gà xé",
                            Price = 30000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 6,
                            Code = "MI01",
                            IsAvailable = true,
                            Name = "Mì xào bò",
                            Price = 27000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 7,
                            Code = "MI02",
                            IsAvailable = true,
                            Name = "Mì Quảng gà",
                            Price = 30000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 8,
                            Code = "PH01",
                            IsAvailable = true,
                            Name = "Phở bò tái",
                            Price = 32000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 9,
                            Code = "PH02",
                            IsAvailable = true,
                            Name = "Phở gà",
                            Price = 30000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 10,
                            Code = "BU01",
                            IsAvailable = true,
                            Name = "Bún chả cá",
                            Price = 28000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 11,
                            Code = "BU02",
                            IsAvailable = true,
                            Name = "Bún bò Huế",
                            Price = 30000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 12,
                            Code = "TR01",
                            IsAvailable = true,
                            Name = "Trà đá",
                            Price = 3000m,
                            Unit = "ly"
                        },
                        new
                        {
                            Id = 13,
                            Code = "TR02",
                            IsAvailable = true,
                            Name = "Trà tắc",
                            Price = 10000m,
                            Unit = "ly"
                        },
                        new
                        {
                            Id = 14,
                            Code = "NC01",
                            IsAvailable = true,
                            Name = "Nước cam ép",
                            Price = 15000m,
                            Unit = "ly"
                        },
                        new
                        {
                            Id = 15,
                            Code = "NS01",
                            IsAvailable = true,
                            Name = "Nước suối",
                            Price = 8000m,
                            Unit = "chai"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CounterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OrderTickets");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderTicketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderTicketId");

                    b.ToTable("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.MenuItem", "MenuItem")
                        .WithMany("TicketLines")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCanteen.Data.Entities.OrderTicket", "OrderTicket")
                        .WithMany("TicketLines")
                        .HasForeignKey("OrderTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Navigation("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Navigation("TicketLines");
                });
#pragma warning restore 612, 618
        }
    }
}
