// <auto-generated />
using System;
using FCanteen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCanteen.Data.Migrations
{
    [DbContext(typeof(FCanteenContext))]
    [Migration("20260929024934_AddIngredientUnitCost")]
    partial class AddIngredientUnitCost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCanteen.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Món chính"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Món phụ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Đồ uống"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tráng miệng"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.DailySettlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CalculationTimeMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailySettlements");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.DiscountPolicyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountOff")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderTicketId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderTicketId");

                    b.ToTable("DiscountPolicyLogs");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WarningThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gạo",
                            StockQuantity = 200m,
                            Unit = "kg",
                            UnitCost = 20000m,
                            WarningThreshold = 20m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thịt gà",
                            StockQuantity = 100m,
                            Unit = "kg",
                            UnitCost = 80000m,
                            WarningThreshold = 15m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thịt heo",
                            StockQuantity = 100m,
                            Unit = "kg",
                            UnitCost = 100000m,
                            WarningThreshold = 15m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thịt bò",
                            StockQuantity = 80m,
                            Unit = "kg",
                            UnitCost = 250000m,
                            WarningThreshold = 10m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rau các loại",
                            StockQuantity = 150m,
                            Unit = "kg",
                            UnitCost = 15000m,
                            WarningThreshold = 20m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Trứng gà",
                            StockQuantity = 500m,
                            Unit = "quả",
                            UnitCost = 3000m,
                            WarningThreshold = 50m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dầu ăn",
                            StockQuantity = 50m,
                            Unit = "lít",
                            UnitCost = 40000m,
                            WarningThreshold = 5m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Nước mắm",
                            StockQuantity = 30m,
                            Unit = "lít",
                            UnitCost = 35000m,
                            WarningThreshold = 5m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Đường",
                            StockQuantity = 40m,
                            Unit = "kg",
                            UnitCost = 18000m,
                            WarningThreshold = 5m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bún/Mì/Phở khô",
                            StockQuantity = 100m,
                            Unit = "kg",
                            UnitCost = 25000m,
                            WarningThreshold = 15m
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CM01",
                            IsAvailable = true,
                            Name = "Cơm gà xối mỡ",
                            Price = 35000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CM02",
                            IsAvailable = true,
                            Name = "Cơm sườn bì chả",
                            Price = 32000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CM03",
                            IsAvailable = true,
                            Name = "Cơm tấm sườn nướng",
                            Price = 30000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CM04",
                            IsAvailable = true,
                            Name = "Cơm chiên dương châu",
                            Price = 28000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CM05",
                            IsAvailable = true,
                            Name = "Cơm gà xé",
                            Price = 30000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 6,
                            Code = "MI01",
                            IsAvailable = true,
                            Name = "Mì xào bò",
                            Price = 27000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 7,
                            Code = "MI02",
                            IsAvailable = true,
                            Name = "Mì Quảng gà",
                            Price = 30000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 8,
                            Code = "PH01",
                            IsAvailable = true,
                            Name = "Phở bò tái",
                            Price = 32000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 9,
                            Code = "PH02",
                            IsAvailable = true,
                            Name = "Phở gà",
                            Price = 30000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 10,
                            Code = "BU01",
                            IsAvailable = true,
                            Name = "Bún chả cá",
                            Price = 28000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 11,
                            Code = "BU02",
                            IsAvailable = true,
                            Name = "Bún bò Huế",
                            Price = 30000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 12,
                            Code = "TR01",
                            IsAvailable = true,
                            Name = "Trà đá",
                            Price = 3000m,
                            Unit = "ly"
                        },
                        new
                        {
                            Id = 13,
                            Code = "TR02",
                            IsAvailable = true,
                            Name = "Trà tắc",
                            Price = 10000m,
                            Unit = "ly"
                        },
                        new
                        {
                            Id = 14,
                            Code = "NC01",
                            IsAvailable = true,
                            Name = "Nước cam ép",
                            Price = 15000m,
                            Unit = "ly"
                        },
                        new
                        {
                            Id = 15,
                            Code = "NS01",
                            IsAvailable = true,
                            Name = "Nước suối",
                            Price = 8000m,
                            Unit = "chai"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItemIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuItemIngredients");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CounterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OrderTickets");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchCode = "CS01",
                            FullName = "Nguyễn Văn A",
                            Role = "Teacher",
                            StaffCode = "GV001"
                        },
                        new
                        {
                            Id = 2,
                            BranchCode = "CS02",
                            FullName = "Trần Thị B",
                            Role = "Teacher",
                            StaffCode = "GV002"
                        },
                        new
                        {
                            Id = 3,
                            BranchCode = "CS01",
                            FullName = "Lê Văn C",
                            Role = "Staff",
                            StaffCode = "NV001"
                        },
                        new
                        {
                            Id = 4,
                            BranchCode = "CS03",
                            FullName = "Phạm Thị D",
                            Role = "Staff",
                            StaffCode = "NV002"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderTicketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderTicketId");

                    b.ToTable("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.DiscountPolicyLog", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.OrderTicket", "OrderTicket")
                        .WithMany()
                        .HasForeignKey("OrderTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItemIngredient", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCanteen.Data.Entities.MenuItem", "MenuItem")
                        .WithMany("MenuItemIngredients")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.MenuItem", "MenuItem")
                        .WithMany("TicketLines")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCanteen.Data.Entities.OrderTicket", "OrderTicket")
                        .WithMany("TicketLines")
                        .HasForeignKey("OrderTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Navigation("MenuItemIngredients");

                    b.Navigation("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Navigation("TicketLines");
                });
#pragma warning restore 612, 618
        }
    }
}
